### ISSUE TITLE
dockerhub rate limit issue (katacoda)

### ISSUE THREAD

**Issue by eitansuez** [kube-academy/katacoda-scenarios#9]
we have seen folks who try to run these katacoda scenarios in kube academy run into issues due to docker hub rate limiting.

see if can either cache images or revise image references to not fetch images from docker hub.
for example, consider using another public registry.
need to investigate what docker hub alternatives are out there and whether they host the images in question.

**Comment by jonasmit** [comment]
@eitansuez will take a look.  For katacoda labs they still use dockerhub so rate limiting is impactful.
